version: "3.8"

services:
  app:
    build:
      context: .
    container_name: clusteredData-warehouse
    depends_on:
      - db
    ports:
      - "8070:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5678/clusteredDataWarehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=879470

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=879470
      - POSTGRES_DATABASE=clusteredDataWarehouse
    ports:
      - "5678:5678"